### PR TITLE
Team page!!

### PR DESCRIPTION
**Pull request by SaptakS**
90% of the credit goes to @Schubisu for this.

- [x] Cleaned up styling
- [x] Add data for all team members

How it looks in my system:
screen shot 2018-06-17 at 3

* Does anyone have any strong opinion about whether the images should be square or circular?
* I have purposefully omitted bio since I find it difficult to write bio. I am not good in bio. I am more of a maths, physics, computer guy. But if anyone feels strongly about bio, I will add that back.
* Does this pic of Schubisu need to be changed? @Schubisu why you do this?!!

### CODE REVIEW

**Comment by jasonbraganza** [comment]
square or circular, whichever looks prettier. or whichever is easy :)

question, is it possible to add a web site link alongside the twitter/gihub icons? 
the blog is my home, not the other two

**Comment by SaptakS** [comment]
> square or circular, whichever looks prettier. or whichever is easy :)

Both are easy. Pretty, it's more of a preference I think.

> is it possible to add a web site link alongside the twitter/gihub icons?

Yup. Your wish is my command.

**Comment by kushaldas** [comment]
The homepage/blog link is a good thing to have (better than github in my mind).

**Comment by kushaldas** [comment]
Looks good, @SaptakS feel free to merge when you think the page is ready. I will deploy (the auto deployment is broken as of now).

**Comment by SaptakS** [comment]
> The homepage/blog link is a good thing to have (better than github in my mind).

Makes sense.

**Comment by SaptakS** [comment]
@jasonbraganza @kushaldas This is the circular one:
screen shot 2018-06-17 at 12


Tell which is pretty

**Comment by farhaanbukhsh** [comment]
Looks good to me 👍

**Comment by Schubisu** [comment]
@SaptakS nice, that looks really cool! I think I like the circular images more. See my [PR](https://github.com/SaptakS/lektorweb/pull/1) for minor adds.

**Pull request merged**
